version: '3'

tasks:
  build:
    vars:
      GOARCH: amd64
      GOOS: linux
    cmds:
      - GOARCH={{.GOARCH}} GOOS={{.GOOS}} go build -o bin/catalyst main.go
    sources:
      - '**/*.go'
    generates:
      - bin/catalyst
